services:
  # Backend (Web Service) - api.pastefind.com
  - type: web
    name: pastefind-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    branch: main
    region: oregon
    customDomains:
      - pastefind.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PATH
        value: /var/www/pastefind-backend/bin:$PATH

