services:
  # The Backend (API)
  - type: web
    name: pastefind-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  # The Frontend (React/Vite Site)
  - type: static
    name: pastefind-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    plan: free
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
