services:
  # Backend (Web Service) - api.pastefind.com
  - type: web
    name: pastefind-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    branch: main
    region: oregon
    customDomains:
      - pastefind.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

